apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-debate-deployment
  labels:
    app: stock-debate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-debate
  template:
    metadata:
      labels:
        app: stock-debate
    spec:
      containers:
        - name: authentication-service
          image: authentication-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081