server:
  port: 9080

kubernetes:
  ingress:
    ip: 172.20.95.18

zuul:
  routes:
    authentication-service:
      path: /authentication/**
      url: http://${kubernetes.ingress.ip}/authentication
    stock-debate-api:
      path: /stock-debate-api/**
      url: http://${kubernetes.ingress.ip}/stock-debate-api
    stock-service:
      path: /stock/**
      url: http://${kubernetes.ingress.ip}/stock
    discussion-service:
      path: /discussion/**
      url: http://${kubernetes.ingress.ip}/discussion
    community-service:
      path: /community/**
      url: http://${kubernetes.ingress.ip}/community

#server:
#  port: 9080
#
#kubernetes:
#  ingress:
#    ip: 172.17.120.212
#
#zuul:
#  routes:
#    authentication-service:
#      path: /search-service/**
#      url: http://${kubernetes.ingress.ip}/search-service
##    stock-debate-api:
##      path: /stock-debate-api/**
##      url: http://${kubernetes.ingress.ip}/stock-debate-api
##    stock-service:
##      path: /stock/**
##      url: http://${kubernetes.ingress.ip}/stock
##    discussion-service:
##      path: /discussion/**
##      url: http://${kubernetes.ingress.ip}/discussion
##    community-service:
##      path: /community/**
##      url: http://${kubernetes.ingress.ip}/community
