server:
  port: 8083
spring:
  datasource:
    # temporary data storage
#    url: jdbc:h2:mem:testdb
    # temporary data storage
    url: jdbc:h2:file:C:/Dev/h2databases/stock
    driverClassName: org.h2.Driver
    username: admin
  h2:
    console:
      enabled: true
      path: /database
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update