server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:/Dev/h2databases/discussion
    driverClassName: org.h2.Driver
    username: admin
  h2:
    console:
      enabled: true
      path: /database
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
security:
  oauth2:
    client:
      grantType: acces_token
      clientId: NhxpfVe5ldAnbA
      clientSecret: 6Br7EqV3FF_5ekQeOGUMiEsoo1Gzhg
      accessTokenUri: https://www.reddit.com/api/v1/access_token