apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: stock-debate
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000

#localhost:3000 does not work, but minikube service <metadata.name> works