apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-deployment
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: authentication-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /Dev/h2databases
              name: h2-databases-volume
      volumes:
        - name: h2-databases-volume
          hostPath:
            path: /h2databases
            type: Directory